import { CodeChunk, ZoomImage } from "@/components";
import { Li, Ul } from "@ui/list";
import { P } from "@ui/paragraph";
import { Table, Td, Th } from "@ui/table";
import type { SectionsProps } from "@/types";

export const Sections: SectionsProps = ({ imagePath }) => [
  {
    title: "網絡資料的格式",
    content: (
      <>
        <P>
          <b>無方向性（Undirected, Binary）</b>
        </P>
        <ZoomImage className="w-lg-50 w-sm-75 mx-auto img-invert" src={`${imagePath}/r003_1.png`} />
        <Table>
          <caption>Adjacency List</caption>
          <thead>
            <tr>
              <Th>ego</Th>
              <Th>alter1</Th>
              <Th>alter2</Th>
              <Th>alter3</Th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <Td>a</Td>
              <Td>b</Td>
              <Td>.</Td>
              <Td>.</Td>
            </tr>
            <tr>
              <Td>b</Td>
              <Td>a</Td>
              <Td>c</Td>
              <Td>.</Td>
            </tr>
            <tr>
              <Td>c</Td>
              <Td>b</Td>
              <Td>d</Td>
              <Td>e</Td>
            </tr>
            <tr>
              <Td>d</Td>
              <Td>c</Td>
              <Td>e</Td>
              <Td>.</Td>
            </tr>
            <tr>
              <Td>e</Td>
              <Td>c</Td>
              <Td>d</Td>
              <Td>.</Td>
            </tr>
          </tbody>
        </Table>
        <Table>
          <caption>Matrices</caption>
          <tbody>
            <tr>
              <Th>.</Th>
              <Th>a</Th>
              <Th>b</Th>
              <Th>c</Th>
              <Th>d</Th>
              <Th>e</Th>
            </tr>
            <tr>
              <Th>a</Th>
              <Td>0</Td>
              <Td>1</Td>
              <Td>0</Td>
              <Td>0</Td>
              <Td>0</Td>
            </tr>
            <tr>
              <Th>b</Th>
              <Td>1</Td>
              <Td>0</Td>
              <Td>1</Td>
              <Td>0</Td>
              <Td>0</Td>
            </tr>
            <tr>
              <Th>c</Th>
              <Td>0</Td>
              <Td>1</Td>
              <Td>0</Td>
              <Td>1</Td>
              <Td>1</Td>
            </tr>
            <tr>
              <Th>d</Th>
              <Td>0</Td>
              <Td>0</Td>
              <Td>1</Td>
              <Td>0</Td>
              <Td>1</Td>
            </tr>
            <tr>
              <Th>e</Th>
              <Td>0</Td>
              <Td>0</Td>
              <Td>1</Td>
              <Td>1</Td>
              <Td>0</Td>
            </tr>
          </tbody>
        </Table>
        <Table>
          <caption>Arc List</caption>
          <tbody>
            <tr>
              <Th>vertex</Th>
              <Th>vertex</Th>
            </tr>
            <tr>
              <Td>a</Td>
              <Td>b</Td>
            </tr>
            <tr>
              <Td>b</Td>
              <Td>a</Td>
            </tr>
            <tr>
              <Td>b</Td>
              <Td>c</Td>
            </tr>
            <tr>
              <Td>c</Td>
              <Td>b</Td>
            </tr>
            <tr>
              <Td>c</Td>
              <Td>d</Td>
            </tr>
            <tr>
              <Td>c</Td>
              <Td>e</Td>
            </tr>
            <tr>
              <Td>d</Td>
              <Td>c</Td>
            </tr>
            <tr>
              <Td>d</Td>
              <Td>e</Td>
            </tr>
            <tr>
              <Td>e</Td>
              <Td>c</Td>
            </tr>
            <tr>
              <Td>e</Td>
              <Td>d</Td>
            </tr>
          </tbody>
        </Table>
        <P>
          <b>有方向性（Directed, Binary）</b>
        </P>
        <ZoomImage className="w-lg-50 w-sm-75 mx-auto img-invert" src={`${imagePath}/r003_2.png`} />
        <Table>
          <caption>Matrices</caption>
          <tbody>
            <tr>
              <Th>.</Th>
              <Th>a</Th>
              <Th>b</Th>
              <Th>c</Th>
              <Th>d</Th>
              <Th>e</Th>
            </tr>
            <tr>
              <Th>a</Th>
              <Td>0</Td>
              <Td>1</Td>
              <Td>0</Td>
              <Td>0</Td>
              <Td>0</Td>
            </tr>
            <tr>
              <Th>b</Th>
              <Td>1</Td>
              <Td>0</Td>
              <Td>0</Td>
              <Td>0</Td>
              <Td>0</Td>
            </tr>
            <tr>
              <Th>c</Th>
              <Td>0</Td>
              <Td>1</Td>
              <Td>0</Td>
              <Td>1</Td>
              <Td>1</Td>
            </tr>
            <tr>
              <Th>d</Th>
              <Td>0</Td>
              <Td>0</Td>
              <Td>0</Td>
              <Td>0</Td>
              <Td>0</Td>
            </tr>
            <tr>
              <Th>e</Th>
              <Td>0</Td>
              <Td>0</Td>
              <Td>1</Td>
              <Td>1</Td>
              <Td>0</Td>
            </tr>
          </tbody>
        </Table>
        <P>
          <b>無方向性，有強弱差異（Undirected, Valued）</b>
        </P>
        <ZoomImage className="w-lg-50 w-sm-75 mx-auto img-invert" src={`${imagePath}/r003_3.png`} />
        <Table>
          <caption>Edgelist</caption>
          <tbody>
            <tr>
              <Th>ego</Th>
              <Th>alter</Th>
              <Th>relation</Th>
            </tr>
            <tr>
              <Td>a</Td>
              <Td>b</Td>
              <Td>1</Td>
            </tr>
            <tr>
              <Td>b</Td>
              <Td>a</Td>
              <Td>1</Td>
            </tr>
            <tr>
              <Td>b</Td>
              <Td>c</Td>
              <Td>3</Td>
            </tr>
            <tr>
              <Td>c</Td>
              <Td>b</Td>
              <Td>3</Td>
            </tr>
            <tr>
              <Td>c</Td>
              <Td>d</Td>
              <Td>1</Td>
            </tr>
            <tr>
              <Td>c</Td>
              <Td>e</Td>
              <Td>4</Td>
            </tr>
            <tr>
              <Td>d</Td>
              <Td>c</Td>
              <Td>1</Td>
            </tr>
            <tr>
              <Td>d</Td>
              <Td>e</Td>
              <Td>2</Td>
            </tr>
            <tr>
              <Td>e</Td>
              <Td>c</Td>
              <Td>4</Td>
            </tr>
            <tr>
              <Td>e</Td>
              <Td>d</Td>
              <Td>2</Td>
            </tr>
          </tbody>
        </Table>
        <P>
          <b>有方向性，有強弱差異（Directed, Valued）</b>
        </P>
        <ZoomImage className="w-lg-50 w-sm-75 mx-auto img-invert" src={`${imagePath}/r003_4.png`} />
        <Table>
          <caption>Edgelist</caption>
          <tbody>
            <tr>
              <Th>ego</Th>
              <Th>alter</Th>
              <Th>relation</Th>
            </tr>
            <tr>
              <Td>a</Td>
              <Td>b</Td>
              <Td>2</Td>
            </tr>
            <tr>
              <Td>b</Td>
              <Td>a</Td>
              <Td>1</Td>
            </tr>
            <tr>
              <Td>c</Td>
              <Td>b</Td>
              <Td>1</Td>
            </tr>
            <tr>
              <Td>c</Td>
              <Td>d</Td>
              <Td>1</Td>
            </tr>
            <tr>
              <Td>c</Td>
              <Td>e</Td>
              <Td>3</Td>
            </tr>
            <tr>
              <Td>e</Td>
              <Td>d</Td>
              <Td>3</Td>
            </tr>
            <tr>
              <Td>e</Td>
              <Td>c</Td>
              <Td>2</Td>
            </tr>
          </tbody>
        </Table>
      </>
    ),
  },
  {
    title: "網絡分析基本概念",
    content: (
      <>
        <Ul>
          <Li>
            相通性（Reachability）：
            <ZoomImage className="w-lg-25 w-sm-50 mx-auto img-invert" src={`${imagePath}/r003_5.png`} />
            <P>
              X<sup>n</sup>=在n步之內，有多少條路徑可連回actors
              <br />
              可利用矩陣次方進行計算
              <br />
            </P>
            <CodeChunk code={`X <- matrix(c(0,1,0,0,0,1,\n  1,0,1,0,0,0,\n  0,1,0,1,1,1,\n  0,0,1,0,1,0,\n  0,0,1,1,0,0,\n  1,0,1,0,0,0), 6, byrow = T)\nX`} lang="r" />
            <CodeChunk code={`##      [,1] [,2] [,3] [,4] [,5] [,6]\n## [1,]    0    1    0    0    0    1\n## [2,]    1    0    1    0    0    0\n## [3,]    0    1    0    1    1    1\n## [4,]    0    0    1    0    1    0\n## [5,]    0    0    1    1    0    0\n## [6,]    1    0    1    0    0    0`} lang="output" />
            <CodeChunk code={`X2 <- X %^% 2\n# 例：在兩步之內能連結到a的有\n# a-b-a\n# a-f-a\n# c-b-a\n# c-f-a\n# 因此[a,a]=2 [a,c]=2\nX2`} lang="r" />
            <CodeChunk code={`##      [,1] [,2] [,3] [,4] [,5] [,6]\n## [1,]    2    0    2    0    0    0\n## [2,]    0    2    0    1    1    2\n## [3,]    2    0    4    1    1    0\n## [4,]    0    1    1    2    1    1\n## [5,]    0    1    1    1    2    1\n## [6,]    0    2    0    1    1    2`} lang="output" />
          </Li>
          <Li>Degree：與其他actors的直接連結數目</Li>
          <Li>In-degree：從其他actors接收的連結</Li>
          <Li>
            Out-degree：發送給其他actors的連結
            <ZoomImage className="w-lg-50 w-sm-75 mx-auto img-invert" src={`${imagePath}/r003_6.png`} />
            <Table>
              <tbody>
                <tr>
                  <Th>.</Th>
                  <Th>a</Th>
                  <Th>b</Th>
                  <Th>c</Th>
                  <Th>d</Th>
                  <Th>e</Th>
                </tr>
                <tr>
                  <Th>a</Th>
                  <Td>0</Td>
                  <Td>1</Td>
                  <Td>0</Td>
                  <Td>0</Td>
                  <Td>0</Td>
                </tr>
                <tr>
                  <Th>b</Th>
                  <Td>1</Td>
                  <Td>0</Td>
                  <Td>0</Td>
                  <Td>0</Td>
                  <Td>0</Td>
                </tr>
                <tr>
                  <Th>c</Th>
                  <Td>0</Td>
                  <Td>1</Td>
                  <Td>0</Td>
                  <Td>1</Td>
                  <Td>1</Td>
                </tr>
                <tr>
                  <Th>d</Th>
                  <Td>0</Td>
                  <Td>0</Td>
                  <Td>0</Td>
                  <Td>0</Td>
                  <Td>0</Td>
                </tr>
                <tr>
                  <Th>e</Th>
                  <Td>0</Td>
                  <Td>0</Td>
                  <Td>1</Td>
                  <Td>1</Td>
                  <Td>0</Td>
                </tr>
              </tbody>
            </Table>
            <Table>
              <tbody>
                <tr>
                  <Th>Node</Th>
                  <Th>In-Degree</Th>
                  <Th>Out-Degree</Th>
                </tr>
                <tr>
                  <Td>a</Td>
                  <Td>1</Td>
                  <Td>1</Td>
                </tr>
                <tr>
                  <Td>b</Td>
                  <Td>2</Td>
                  <Td>1</Td>
                </tr>
                <tr>
                  <Td>c</Td>
                  <Td>1</Td>
                  <Td>3</Td>
                </tr>
                <tr>
                  <Td>d</Td>
                  <Td>2</Td>
                  <Td>0</Td>
                </tr>
                <tr>
                  <Td>e</Td>
                  <Td>1</Td>
                  <Td>2</Td>
                </tr>
                <tr>
                  <Td>Mean</Td>
                  <Td>7/5</Td>
                  <Td>7/5</Td>
                </tr>
              </tbody>
            </Table>
          </Li>
          <Li>
            度中心性（Degree Centrality）：能連結到的數量 / 總數-1
            <img className="d-block mx-auto img-invert" src={`${imagePath}/degree_centrality.svg`} alt="degree_centrality" />
            <P>
              <i>
                A<sub>ij</sub>
              </i>{" "}
              = socio-matrix
            </P>
          </Li>
          <Li>
            接近中心性（Closeness Centrality）：與其他actors的鄰近程度
            <img className="d-block mx-auto img-invert" src={`${imagePath}/closeness_centrality.svg`} alt="closeness_centrality" />
            <P>
              <i>
                d<sub>ij</sub>
              </i>{" "}
              = 到每個actors的距離
            </P>
          </Li>
          <Li>
            界數中心性（Betweenness Centrality）：兩actors經過第三actor的最短路徑數
            <img className="d-block mx-auto img-invert" src={`${imagePath}/betweenness_centrality.svg`} alt="betweenness_centrality" />
            <P>
              <i>
                G<sub>jk</sub>
              </i>{" "}
              = jk之間的最短路徑
              <br />
              <i>
                G<sub>jik</sub>
              </i>{" "}
              = jk之間，經過i的最短路徑
              <br />
            </P>
          </Li>
          <Li>
            網絡密度（Density）：
            <img className="d-block mx-auto img-invert" src={`${imagePath}/density.svg`} alt="density" />
            <P>
              實際存在的路徑數/最多可能路徑數
              <br />
              <i>N</i> = actors數量
              <br />
            </P>
          </Li>
        </Ul>
      </>
    ),
  },
];
