version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    command: --auth --config /etc/mongo/mongod.conf
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydb
      GLIBC_TUNABLES: glibc.pthread.rseq=0
      TZ: Asia/Taipei
    volumes: 
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./database/configdb:/data/configdb
      - ./database/data:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf
    ports: 
      - '27017:27017'
